### ISSUE TITLE
Example of synonym_types.txt?

### ISSUE THREAD

**Issue by cbnfreitas** [DiceTechJobs/SolrConfigExamples#1]
The file top_n_field_type.xml refers to:

 filter to just tokens in the file above 

filter class="solr.TypeTokenFilterFactory" types="synonym_types.txt" useWhitelist="true"

Could you please provide an example of it?

**Comment by phpgurru** [comment]
@cbnfreitas  I am also stuck at this point. Can you please share details if you had successfully implemented synonyms.

Thanks

**Comment by simonhughes22** [comment]
Sorry must have missed this. @cbnfreitas @phpgurru  - it's just a text file with the content 'SYNONYM' in it (that's it). This is standard solr functionality.
